version: '2'
services:
  php:
    image: bscheshir/php:7.4.3-fpm-alpine-4yii2
    build:
      context: ./Docker/config/php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html #web
      - ./Docker/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "${TZ:-Europe/Moscow}"
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
    depends_on:
      - db
    links:
      - db


  nginx:
    image: nginx:1.17.8-alpine
    expose:
      - 8080
    ports:
      - 8080:8010
    volumes:
      - .:/var/www/html #web
      - ./Docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf #nginx-conf
      - ./Docker/config/nginx:/var/log/nginx #nginx-logs
    environment:
      TZ: "${TZ:-Europe/Moscow}"
    depends_on:
      - php


  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 8000:80
    links:
      - db:db

  db:
    image: mysql:latest
    ports:
      - 3300:3306
    volumes:
      - /Docker/data:/var/lib/mysql #
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

volumes:
  db_data: